version: 0.2

phases:
  pre_build: 
    commands:
      - npm install
  build:
    commands:
      - npm run build 
  
  post_build:
    commands:
      - zip -r myapp.zip dist/*

artifacts:
  files:
    - myapp.zip