version: 0.2

phases:
  pre_build: 
    commands:
      - npm install
  build:
    commands:
      - npm run build 
      - aws s3 cp build/syncpro.zip s3://syncpro-bucket/syncpro.zip
  
  post_build:
    commands:
      - ssh ubuntu@18.117.185.57 "sudo unzip /tmp/syncpro.zip -d /var/www/html"
